### ISSUE TITLE
Swagger REST access broken

### ISSUE THREAD

**Issue by christopherkane** [TheQwizTeam/qwiz#58]

**Comment by christopherkane** [comment]
When accessing REST APIs through swagger, seeing random backslash in URL path.

Accessing the resources through the API sees a 404 response, with the following body:

> <!DOCTYPE html>
> <html lang="en">
> <head>
>   <meta http-equiv="content-type" content="text/html; charset=utf-8">
>   <title>Page not found at /api//question/</title>
>   <meta name="robots" content="NONE,NOARCHIVE">
>   <style type="text/css">
>     html * { padding:0; margin:0; }
>     body * { padding:10px 20px; }
>     body * * { padding:0; }
>     body { font:small sans-serif; background:#eee; color:#000; }
>     body>div { border-bottom:1px solid #ddd; }
>     h1 { font-weight:normal; margin-bottom:.4em; }
>     h1 span { font-size:60%; color:#666; font-weight:normal; }
>     table { border:none; border-collapse: collapse; width:100%; }
>     td, th { vertical-align:top; padding:2px 3px; }
>     th { width:12em; text-align:right; color:#666; padding-right:.5em; }
>     #info { background:#f6f6f6; }
>     #info ol { margin: 0.5em 4em; }
>     #info ol li { font-family: monospace; }
>     #summary { background: #ffc; }
>     #explanation { background:#eee; border-bottom: 0px none; }
>   </style>
> </head>
> <body>
>   <div id="summary">
>     <h1>Page not found <span>(404)</span></h1>
>     <table class="meta">
>       <tr>
>         <th>Request Method:</th>
>         <td>GET</td>
>       </tr>
>       <tr>
>         <th>Request URL:</th>
>         <td>http://127.0.0.1:5000/api//question/</td>
>       </tr>
>       
>     </table>
>   </div>
>   <div id="info">
>     
>       <p>
>       Using the URLconf defined in <code>quiz.urls</code>,
>       Django tried these URL patterns, in this order:
>       </p>
>       <ol>
>         
>           <li>
>             
>                 
>                 
>             
>           </li>
>         
>           <li>
>             
>                 swagger/
>                 
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^tags/$
>                 [name='tag-list']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^tags\.(?P&lt;format&gt;[a-z0-9]+)/?$
>                 [name='tag-list']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^tags/(?P&lt;pk&gt;[^/.]+)/$
>                 [name='tag-detail']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^tags/(?P&lt;pk&gt;[^/.]+)\.(?P&lt;format&gt;[a-z0-9]+)/?$
>                 [name='tag-detail']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^room/$
>                 [name='room-list']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^room\.(?P&lt;format&gt;[a-z0-9]+)/?$
>                 [name='room-list']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^room/(?P&lt;pk&gt;[^/.]+)/$
>                 [name='room-detail']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^room/(?P&lt;pk&gt;[^/.]+)\.(?P&lt;format&gt;[a-z0-9]+)/?$
>                 [name='room-detail']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^question/$
>                 [name='question-list']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^question\.(?P&lt;format&gt;[a-z0-9]+)/?$
>                 [name='question-list']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^question/(?P&lt;pk&gt;[^/.]+)/$
>                 [name='question-detail']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^question/(?P&lt;pk&gt;[^/.]+)\.(?P&lt;format&gt;[a-z0-9]+)/?$
>                 [name='question-detail']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^$
>                 [name='api-root']
>             
>           </li>
>         
>           <li>
>             
>                 api/
>                 
>             
>                 ^\.(?P&lt;format&gt;[a-z0-9]+)/?$
>                 [name='api-root']
>             
>           </li>
>         
>           <li>
>             
>                 api-auth
>                 
>             
>           </li>
>         
>           <li>
>             
>                 admin/
>                 
>             
>           </li>
>         
>       </ol>
>       <p>
>         
>         The current path, <code>api//question/</code>, didn't match any of these.
>       </p>
>     
>   </div>
> 
>   <div id="explanation">
>     <p>
>       You're seeing this error because you have <code>DEBUG = True</code> in
>       your Django settings file. Change that to <code>False</code>, and Django
>       will display a standard 404 page.
>     </p>
>   </div>
> </body>
> </html>
> Response Code
> 404

**Comment by pgcrooks** [comment]
I have a fix for the GET API, however POST still throws an error:

`curl -X POST --header 'Content-Type: application/json' --header 'Accept: text/plain' --header 'X-CSRFToken: JpFS5ZBm9zFRCvMd7pE7JwUkp0VtGBhn96iXksF2E1toUf1VIY7ZSufmoIgv1sML' -d '{ \ 
   "num_questions": 2, \ 
   "name": "brisbane", \ 
   "tags": [ \ 
     "public" \ 
   ] \ 
 }' 'http://localhost:5000/api/room/'`

Response:

`TypeError at /api/room/
Direct assignment to the forward side of a many-to-many set is prohibited. Use questions.set() instead.`

**Comment by pgcrooks** [comment]
Traceback:

`File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  35.             response = get_response(request)

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  128.                 response = self.process_exception_by_middleware(e, request)

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/channels/handler.py" in process_exception_by_middleware
  243.             return super(AsgiHandler, self).process_exception_by_middleware(exception, request)

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  126.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/django/views/decorators/csrf.py" in wrapped_view
  54.         return view_func(*args, **kwargs)

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/rest_framework/viewsets.py" in view
  95.             return self.dispatch(request, *args, **kwargs)

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/rest_framework/views.py" in dispatch
  494.             response = self.handle_exception(exc)

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/rest_framework/views.py" in handle_exception
  454.             self.raise_uncaught_exception(exc)

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/rest_framework/views.py" in dispatch
  491.             response = handler(request, *args, **kwargs)

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/rest_framework/mixins.py" in create
  21.         self.perform_create(serializer)

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/rest_framework/mixins.py" in perform_create
  26.         serializer.save()

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/rest_framework/serializers.py" in save
  214.             self.instance = self.create(validated_data)

File "/home/pcrooks/Documents/projects/qwiz/quiz/serialisers.py" in create
  38.         room.populate(tags, num_questions)

File "/home/pcrooks/Documents/projects/qwiz/quiz/models.py" in populate
  101.         self.questions = questions[:num_questions]

File "/home/pcrooks/.virtualenvs/qwiz/lib/python3.5/site-packages/django/db/models/fields/related_descriptors.py" in __set__
  509.             % self._get_set_deprecation_msg_params(),`
